// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizGame.Repository.Models
{
    public partial class Game
    {
        public Game()
        {
            GameLogs = new HashSet<GameLog>();
            Players = new HashSet<Player>();
            QuestionInGames = new HashSet<QuestionInGame>();
            Teams = new HashSet<Team>();
        }

        public int   GameId { get; set; }
        public string   GameName { get; set; }
        public int? HostId { get; set; }
        public string GamePin { get; set; }
        public string Status { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }
        public int? QuizId { get; set; }

        public virtual User Host { get; set; }
        public virtual Quiz Quiz { get; set; }
        public virtual ICollection<GameLog> GameLogs { get; set; }
        public virtual ICollection<Player> Players { get; set; }
        public virtual ICollection<QuestionInGame> QuestionInGames { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
    }
}