// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizGame.Repository.Models;

public partial class Game
{
    public int GameId { get; set; }

    public string GameName { get; set; }

    public int? HostId { get; set; }

    public string GamePin { get; set; }

    public string Status { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public int? QuizId { get; set; }

    public virtual ICollection<GameLog> GameLogs { get; set; } = new List<GameLog>();

    public virtual User Host { get; set; }

    public virtual ICollection<Player> Players { get; set; } = new List<Player>();

    public virtual ICollection<QuestionInGame> QuestionInGames { get; set; } = new List<QuestionInGame>();

    public virtual Quiz Quiz { get; set; }

    public virtual ICollection<Team> Teams { get; set; } = new List<Team>();
}