// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizGame.Repository.Models;

public partial class GameLog
{
    public int LogId { get; set; }

    public int? GameId { get; set; }

    public string Action { get; set; }

    public DateTime? ActionTime { get; set; }

    public virtual Game Game { get; set; }
}