// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizGame.Repository.Models
{
    public partial class PlayerAnswer
    {
        public int PlayerAnswerId { get; set; }
        public int? PlayerId { get; set; }
        public int? QuestionInGameId { get; set; }
        public string Answer { get; set; }
        public bool? IsCorrect { get; set; }
        public int? TimeTaken { get; set; }

        public virtual Player Player { get; set; }
        public virtual QuestionInGame QuestionInGame { get; set; }
    }
}