// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizGame.Repository.Models;

public partial class QuestionInGame
{
    public int QuestionInGameId { get; set; }

    public int? QuestionId { get; set; }

    public int? GameId { get; set; }

    public int QuestionNumber { get; set; }

    public virtual Game Game { get; set; }

    public virtual ICollection<PlayerAnswer> PlayerAnswers { get; set; } = new List<PlayerAnswer>();

    public virtual Question Question { get; set; }

    public virtual ICollection<TeamScore> TeamScores { get; set; } = new List<TeamScore>();
}