// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizGame.Repository.Models
{
    public partial class Quiz
    {
        public Quiz()
        {
            Games = new HashSet<Game>();
            Questions = new HashSet<Question>();
        }

        public int QuizId { get; set; }
        public string QuizName { get; set; }

        public virtual ICollection<Game> Games { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}